#! /usr/bin/env /bin/bash

set -euo pipefail

BASEDIR=$(dirname "$0")
BUILDER=${DOCKER_BUILDER:-container-builder}
REGISTRY_NAME=${DOCKER_REGISTRY_REPO:-registry}
REGISTRY_IMAGE=${DOCKER_REGISTRY_IMAGE:-registry:2}
REGISTRY_PORT=${DOCKER_REGISTRY_PORT:-5000}

function check_registry() {
  local result=$(docker ps -aq -f "name=${REGISTRY_NAME}")
  if [[ "${result}" == "" ]] ; then
    echo "1"
  else
    echo "0"
  fi
}

if [[ "$(check_registry)" != "0" ]] ; then
  echo "creating local registry"
  docker run --name "${REGISTRY_NAME}" \
    --restart always \
    --publish ${REGISTRY_PORT}:5000 \
    --detach "${REGISTRY_IMAGE}"
fi


function check_builder() {
  docker buildx inspect "${BUILDER}" 2>&1 > /dev/null
  echo $?
}

if [[ "$(check_builder)" != "0" ]] ; then
  echo "creating builder instance"
  docker buildx create --name "${BUILDER}" \
    --driver docker-container \
    --driver-opt network=host \
    --config ${BASEDIR}/buildx.toml \
    --bootstrap
fi
